// Code generated by "stringer -type Opcode"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConstant-0]
	_ = x[OpPop-1]
	_ = x[OpAdd-2]
	_ = x[OpSub-3]
	_ = x[OpMult-4]
	_ = x[OpDiv-5]
	_ = x[OpMod-6]
	_ = x[lastOpcode-7]
}

const _Opcode_name = "OpConstantOpPopOpAddOpSubOpMultOpDivOpModlastOpcode"

var _Opcode_index = [...]uint8{0, 10, 15, 20, 25, 31, 36, 41, 51}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
