// Code generated by "stringer -type=Type"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NullType-0]
	_ = x[IntegerType-1]
	_ = x[FloatType-2]
	_ = x[BoolType-3]
	_ = x[StringType-4]
	_ = x[FunctionType-5]
	_ = x[BuiltinType-6]
	_ = x[ArrayType-7]
	_ = x[ReturnType-8]
	_ = x[ContinueType-9]
	_ = x[BreakType-10]
	_ = x[ErrorType-11]
}

const _Type_name = "NullTypeIntegerTypeFloatTypeBoolTypeStringTypeFunctionTypeBuiltinTypeArrayTypeReturnTypeContinueTypeBreakTypeErrorType"

var _Type_index = [...]uint8{0, 8, 19, 28, 36, 46, 58, 69, 78, 88, 100, 109, 118}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
