// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[LPar-1]
	_ = x[RPar-2]
	_ = x[LBrace-3]
	_ = x[RBrace-4]
	_ = x[LBrack-5]
	_ = x[RBrack-6]
	_ = x[Comma-7]
	_ = x[Dot-8]
	_ = x[Pipe-9]
	_ = x[SemiColon-10]
	_ = x[Plus-11]
	_ = x[Minus-12]
	_ = x[Mult-13]
	_ = x[Div-14]
	_ = x[Mod-15]
	_ = x[Bang-16]
	_ = x[NEQ-17]
	_ = x[Assign-18]
	_ = x[EQ-19]
	_ = x[GT-20]
	_ = x[GTE-21]
	_ = x[LT-22]
	_ = x[LTEQ-23]
	_ = x[Ident-24]
	_ = x[String-25]
	_ = x[Int-26]
	_ = x[Hex-27]
	_ = x[Oct-28]
	_ = x[Bin-29]
	_ = x[Float-30]
	_ = x[Comment-31]
	_ = x[keywordStart-32]
	_ = x[Class-33]
	_ = x[Super-34]
	_ = x[Self-35]
	_ = x[Func-36]
	_ = x[Return-37]
	_ = x[Let-38]
	_ = x[If-39]
	_ = x[Else-40]
	_ = x[And-41]
	_ = x[Or-42]
	_ = x[For-43]
	_ = x[While-44]
	_ = x[True-45]
	_ = x[False-46]
	_ = x[Nil-47]
	_ = x[keywordEnd-48]
	_ = x[Newline-49]
	_ = x[EOF-50]
	_ = x[end-51]
}

const _Type_name = "unknown(){}[],.|;+-*/%!!====>>=<<=identstringinthexoctbinfloatcommentkeywordStartclasssuperselffnreturnletifelseandorforwhiletruefalsenilkeywordEndNewlineEOFend"

var _Type_index = [...]uint8{0, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 28, 29, 31, 32, 34, 39, 45, 48, 51, 54, 57, 62, 69, 81, 86, 91, 95, 97, 103, 106, 108, 112, 115, 117, 120, 125, 129, 134, 137, 147, 154, 157, 160}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
