// Code generated by "stringer -type builtin -linecomment"; DO NOT EDIT.

package builtins

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[startBuiltin-0]
	_ = x[IntBuiltin-1]
	_ = x[FloatBuiltin-2]
	_ = x[StringBuiltin-3]
	_ = x[LenBuiltin-4]
	_ = x[PopBuiltin-5]
	_ = x[PrintBuiltin-6]
	_ = x[AppendBuiltin-7]
	_ = x[SliceBuiltin-8]
	_ = x[endBuiltin-9]
}

const _builtin_name = "startBuiltinintfloatstringlenpopprintappendsliceendBuiltin"

var _builtin_index = [...]uint8{0, 12, 15, 20, 26, 29, 32, 37, 43, 48, 58}

func (i builtin) String() string {
	if i < 0 || i >= builtin(len(_builtin_index)-1) {
		return "builtin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _builtin_name[_builtin_index[i]:_builtin_index[i+1]]
}
