package main

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

func main() {
	if err := run(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func run() error {
	name, fields := os.Args[1], os.Args[2:]
	c := Context{
		Name:   name,
		Fields: make([]Field, len(fields)),
	}
	maxLen := 0
	for i, field := range fields {
		f := Field{}
		f.Name, f.Type, _ = strings.Cut(field, ":")
		maxLen = max(len(f.Name), maxLen)
		c.Fields[i] = f
	}
	for i := range c.Fields {
		c.Fields[i].Padding = strings.Repeat(" ", maxLen-len(c.Fields[i].Name))
	}
	fileTmpl := template.Must(template.New("").Parse(tmpl))
	f, err := os.Create(strings.ToLower(c.Name) + ".go")
	if err != nil {
		return err
	}
	defer f.Close()

	return fileTmpl.Execute(f, c)
}

type Context struct {
	Name   string
	Fields []Field
}

type Field struct {
	Name    string
	Type    string
	Padding string
}

var tmpl = `// CODE GENERATED BY joker/tools/stmt; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"
)

type {{.Name}}Stmt struct {
	{{- range .Fields }}
	{{.Name}}{{ .Padding }} {{.Type}}{{ end }}
}

func (e *{{.Name}}Stmt) node() {}
func (e *{{.Name}}Stmt) stmt() {}

func (e {{.Name}}Stmt) String() string {
	var sb strings.Builder
	sb.WriteString("{{.Name}}Stmt - {")
	{{- range .Fields }}
	fmt.Fprintf(&sb, "\n  {{.Name}}: (%+v)", e.{{.Name}}){{ end }}
	sb.WriteString("\n}")
	return sb.String()
}
`
