// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type BinaryExpr struct {
	Left     Expr
	Right    Expr
	Operator token.Token
}

func (e *BinaryExpr) expr() {}

func (e BinaryExpr) String() string {
	var sb strings.Builder
	sb.WriteString("BinaryExpr - {")
	fmt.Fprintf(&sb, "\n  Left: (%+v)", e.Left)
	fmt.Fprintf(&sb, "\n  Right: (%+v)", e.Right)
	fmt.Fprintf(&sb, "\n  Operator: (%+v)", e.Operator)
	sb.WriteString("\n}")
	return sb.String()
}
