// CODE GENERATED BY joker/tools/stmt; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"
)

type BlockStmt struct {
	Stmts []Stmt
}

func (e *BlockStmt) node() {}
func (e *BlockStmt) stmt() {}

func (e BlockStmt) String() string {
	var sb strings.Builder
	sb.WriteString("BlockStmt - {")
	fmt.Fprintf(&sb, "\n  Stmts: (%+v)", e.Stmts)
	sb.WriteString("\n}")
	return sb.String()
}
