// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type BoolLitExpr struct {
	Token token.Token
	Value bool
}

func (e *BoolLitExpr) expr() {}

func (e BoolLitExpr) String() string {
	var sb strings.Builder
	sb.WriteString("BoolLitExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	fmt.Fprintf(&sb, "\n  Value: (%+v)", e.Value)
	sb.WriteString("\n}")
	return sb.String()
}
