// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type CommentLitExpr struct {
	Token token.Token
	Value string
}

func (e *CommentLitExpr) node() {}
func (e *CommentLitExpr) expr() {}

func (e CommentLitExpr) String() string {
	var sb strings.Builder
	sb.WriteString("CommentLitExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	fmt.Fprintf(&sb, "\n  Value: (%+v)", e.Value)
	sb.WriteString("\n}")
	return sb.String()
}
