// CODE GENERATED BY joker/tools/stmt; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"
)

type ExprStmt struct {
	Expr Expr
}

func (e *ExprStmt) node() {}
func (e *ExprStmt) stmt() {}

func (e ExprStmt) String() string {
	var sb strings.Builder
	sb.WriteString("ExprStmt - {")
	fmt.Fprintf(&sb, "\n  Expr: (%+v)", e.Expr)
	sb.WriteString("\n}")
	return sb.String()
}
