// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type FloatLitExpr struct {
	Token token.Token
	Value float64
}

func (e *FloatLitExpr) expr() {}

func (e FloatLitExpr) String() string {
	var sb strings.Builder
	sb.WriteString("FloatLitExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	fmt.Fprintf(&sb, "\n  Value: (%+v)", e.Value)
	sb.WriteString("\n}")
	return sb.String()
}
