// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type FuncLitExpr struct {
	Token  token.Token
	Params []*IdentExpr
	Body   *BlockStmt
}

func (e *FuncLitExpr) node() {}
func (e *FuncLitExpr) expr() {}

func (e FuncLitExpr) String() string {
	var sb strings.Builder
	sb.WriteString("FuncLitExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	fmt.Fprintf(&sb, "\n  Params: (%+v)", e.Params)
	fmt.Fprintf(&sb, "\n  Body: (%+v)", e.Body)
	sb.WriteString("\n}")
	return sb.String()
}
