// CODE GENERATED BY joker/tools/stmt; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"
)

type FuncStmt struct {
	Name *IdentExpr
	Fn   *FuncLitExpr
}

func (e *FuncStmt) node() {}
func (e *FuncStmt) stmt() {}

func (e FuncStmt) String() string {
	var sb strings.Builder
	sb.WriteString("FuncStmt - {")
	fmt.Fprintf(&sb, "\n  Name: (%+v)", e.Name)
	fmt.Fprintf(&sb, "\n  Fn: (%+v)", e.Fn)
	sb.WriteString("\n}")
	return sb.String()
}
