// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type GroupingExpr struct {
	Expr  Expr
	Token token.Token
}

func (e *GroupingExpr) node() {}
func (e *GroupingExpr) expr() {}

func (e GroupingExpr) String() string {
	var sb strings.Builder
	sb.WriteString("GroupingExpr - {")
	fmt.Fprintf(&sb, "\n  Expr: (%+v)", e.Expr)
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	sb.WriteString("\n}")
	return sb.String()
}
