// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type IdentExpr struct {
	Token token.Token
	Name  string
}

func (e *IdentExpr) node() {}
func (e *IdentExpr) expr() {}

func (e IdentExpr) String() string {
	var sb strings.Builder
	sb.WriteString("IdentExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	fmt.Fprintf(&sb, "\n  Name: (%+v)", e.Name)
	sb.WriteString("\n}")
	return sb.String()
}
