// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type IntLitExpr struct {
	Token token.Token
	Value int64
}

func (e *IntLitExpr) node() {}
func (e *IntLitExpr) expr() {}

func (e IntLitExpr) String() string {
	var sb strings.Builder
	sb.WriteString("IntLitExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	fmt.Fprintf(&sb, "\n  Value: (%+v)", e.Value)
	sb.WriteString("\n}")
	return sb.String()
}
