// CODE GENERATED BY joker/tools/stmt; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"
)

type LetStmt struct {
	Name  string
	Value Expr
}

func (e *LetStmt) node() {}
func (e *LetStmt) stmt() {}

func (e LetStmt) String() string {
	var sb strings.Builder
	sb.WriteString("LetStmt - {")
	fmt.Fprintf(&sb, "\n  Name: (%+v)", e.Name)
	fmt.Fprintf(&sb, "\n  Value: (%+v)", e.Value)
	sb.WriteString("\n}")
	return sb.String()
}
