// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type NilLitExpr struct {
	Token token.Token
}

func (e *NilLitExpr) expr() {}

func (e NilLitExpr) String() string {
	var sb strings.Builder
	sb.WriteString("NilLitExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	sb.WriteString("\n}")
	return sb.String()
}
