// CODE GENERATED BY joker/tools/stmt; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"
)

type ProgramStmt struct {
	Stmts []Stmt
}

func (e *ProgramStmt) node() {}
func (e *ProgramStmt) stmt() {}

func (e ProgramStmt) String() string {
	var sb strings.Builder
	sb.WriteString("ProgramStmt - {")
	fmt.Fprintf(&sb, "\n  Stmts: (%+v)", e.Stmts)
	sb.WriteString("\n}")
	return sb.String()
}
