// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type StringLitExpr struct {
	Token token.Token
	Value string
}

func (e *StringLitExpr) expr() {}

func (e StringLitExpr) String() string {
	var sb strings.Builder
	sb.WriteString("StringLitExpr - {")
	fmt.Fprintf(&sb, "\n  Token: (%+v)", e.Token)
	fmt.Fprintf(&sb, "\n  Value: (%+v)", e.Value)
	sb.WriteString("\n}")
	return sb.String()
}
