// CODE GENERATED BY joker/tools/expr; DO NOT EDIT.
package ast

import (
	"fmt"
	"strings"

	"github.com/jimmykodes/joker/token"
)

type UnaryExpr struct {
	Right    Expr
	Operator token.Token
}

func (e *UnaryExpr) node() {}
func (e *UnaryExpr) expr() {}

func (e UnaryExpr) String() string {
	var sb strings.Builder
	sb.WriteString("UnaryExpr - {")
	fmt.Fprintf(&sb, "\n  Right: (%+v)", e.Right)
	fmt.Fprintf(&sb, "\n  Operator: (%+v)", e.Operator)
	sb.WriteString("\n}")
	return sb.String()
}
